### ISSUE TITLE
alien build failures due to dd utility from Git for Windows 

### ISSUE THREAD

**Issue by shawnlaffan** [PerlAlien/Alien-MSYS#11]
I've hit this issue a few times recently with Alien::geos::af and Alien::gdal on Github Workflows for Windows.  

GH workflows has ```c:/program files/Git/usr/bin``` in its path, and it contains a ```dd.exe```.

The configure scripts for GDAL and GEOS both look for ```dd```, falling back to ```sed``` if it is not found.  The ```dd``` that comes with Git for Windows depends on ```msys-intl-8.dll```, but this is also in the MSYS bin dir, and the MSYS version is earlier in the path when make is run.

The end result is a build that completes, but which has files that cannot be run.  Running ```objdump -p``` on the files shows missing DLLs compared with a successful run.  

At the moment I am using an around hook in the alienfiles to remove ```Git/usr/bin``` from the path, but perhaps Alien::MSYS could add ```dd``` to its list of downloads.  Or document it as a known problem.

**Comment by plicease** [comment]
1. I think removing the git directory from the PATH would be a win in general since there are probably lots of ways it can break things.  Removing from the PATH should probably go in the `Build::Autoconf` plugin on MSWin32.  The tricky part might be detecting the correct path to remove, since the user can install it anywhere.

 2. I am in principal okay with adding `dd` to the share install for `Alien::MSYS`, depending on how much disk that uses.  If we can get a way with fallback to `sed` that would save a little disk and might be worth it if  isn't too much work.

**Comment by shawnlaffan** [comment]
1.
At the moment I'm just using a regexp that looks for Git/usr/bin:  

```perl
  local $ENV{PATH} = $ENV{PATH};
  @PATH = grep {not $_ =~ m|Git[/\\]usr[/\\]bin$|} @PATH;

```

An approach using [Path::Tiny::subsumes](https://metacpan.org/pod/Path::Tiny#subsumes) might be cleaner, although it uses a similar regexp internally anyway.

Checking for non-standard install locations would be harder, and might need a check of one of the contained utilities, or for ```.../usr/bin/../git-bash.exe```.  (Although I now expect other systems with ```.../usr/bin``` in the path could have similar effects).  

2.
The risk with adding ```dd``` is that it becomes a whack-a-mole process as other utilities are needed.  Hopefully there are not many by this time, though.

A fallback to ```/usr/bin/sed -e 4q``` using a wrapper script might work, but that won't cover other uses of ```dd``` by other systems.  Another option is to return an exit code such that it is not used.  Neither is particularly ideal.    

All that said, ```dd``` is about 90-100kb on my system, depending on what provides it (Git bash, WSL, MSYS2).  Downloading it might not be an issue in this case.

**Comment by shawnlaffan** [comment]
And thinking further on 1, the system needs to check that the user has not set ```$ENV{PERL_ALIEN_MSYS_BIN}``` to that dir, and that Alien::MSYS is using it.

**Comment by shawnlaffan** [comment]
If the decision is to install ```dd``` then it is under the msys-coreutils package, which is about 1.5MB across the different archives.

**Comment by zmughal** [comment]
Hello @shawnlaffan, is this fixed for you now? In <https://github.com/PerlAlien/Alien-MSYS/pull/23>, I added the `msys-coreutils-ext` package which contains `dd.exe`.

**Comment by shawnlaffan** [comment]
Thanks @zmughal.  I have not tested but adding ```dd.exe``` to the should be enough to close this issue.
